services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
      - TZ=Asia/Tokyo
    tty: true
    stdin_open: true
    command: "npm run start"
    depends_on:
      - db
    links:
      - db

  db:
    image: mysql:8.0
    env_file:
      - .env
    environment:
      - TZ=Asia/Tokyo
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    restart: always

volumes:
    data:
      driver: local
